version: '3.4'

services:
  xmltocsv:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  uploaderparserapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

